### ISSUE TITLE
Confirm valid PERF_ID use

### ISSUE THREAD

**Issue by skliper** [nasa/sch_lab#1]
Originated by abrown4 (69 on babelfish):

cFE reserves 0-31 perf-ids. Need to confirm ci_lab does not use these.

**Comment by avan989** [comment]
From looking at ci_lab_perfids.h, ci_lab contains these id. 

#define CI_MAIN_TASK_PERF_ID             21 
#define CI_SOCKET_RCV_PERF_ID           24
