### ISSUE TITLE
SCH_LAB does not support sending commands with arguments

### ISSUE THREAD

**Issue by dmknutsen** [nasa/sch_lab#143]
**Is your feature request related to a problem? Please describe.**
sch_lab does not support sending commands with arguments.  This is needed when scheduling messages such as LC's sample action point command & HK's send combined packet command.

**Describe the solution you'd like**
sch_lab supports sending commands with arguments.

**Requester Info**
Dan Knutsen
NASA Goddard

**Comment by skliper** [comment]
Note https://github.com/nasa/LC/issues/76 is somewhat related.  It requests adding a unique MID for sampling all action points intended to support app-to-app messages (no cmd increment, no parameters, etc).

**Comment by dmknutsen** [comment]
Thanks! I like the unique MID concept - it looks like I must have missed it.  I think ultimately we will want both.  We still need to be able to send commands w/args for the HK combined packet + it would be nice to be able to schedule certain watchpoints if desired.
