### ISSUE TITLE
SCH_LAB unused "taskId"

### ISSUE THREAD

**Issue by skliper** [nasa/sch_lab#2]
Originated by glimes (56 on babelfish):

SCH_LAB application retrieves the Task ID for the current task at the top of its main loop, and never uses it.

**Comment by avan989** [comment]
can you clarify? I am not seeing any variables not being used in sch_lab_app.c

**Comment by skliper** [comment]
Unclear what version this applied to, but taskId is no longer in the code.  Looked through babelfish and it wasn't in the master branch and hadn't been touched in years.  Closing issue as invalid.
