### ISSUE TITLE
Improve table handling

### ISSUE THREAD

**Issue by skliper** [nasa/sch_lab#27]
**Is your feature request related to a problem? Please describe.**
Doesn't actually allow table management within the task loop

**Describe the solution you'd like**
Actually follow the table management pattern, allowing updates (should be a decent example)

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Requester Info**
Jacob Hageman - NASA/GSFC

**Comment by jphickey** [comment]
I'm getting back into this code a bit as I'm merging the EDS-related changes to the latest master, and stumbled across some other gripes about the way the tables in SCH_LAB are currently defined:

- Each field in the table structure should not be a separate array.  Rather, the structure definition should reflect a single entry, and then the table definition should be an array of those structures.  This keeps the related fields next to each other in memory, and AFIAK is the preferred/recommended way to organize these data structures.
- The `Counter` field should NOT be part of the table.  There is no reason to put this in the file, it is runtime data and should be allocated in an app-scope global.

Did catch either of these on the initial review, unfortunately.

It is also not clear if the "live" updates to the table during runtime are supposed to be handled.  If not, then SCH_LAB should just read the table once at startup and release it so the buffer memory can be used by another app.  If live update _is_ supposed to be handled, then the code needs to check for table updates and re-initialize its local objects which is not done at all right now.

There seems to be a bit of feature-creep going on here; we already have the full-blown CFS SCH app for users who need a more complete scheduler, which is table-based and supports all the flight-oriented updates that one would need.  The LAB version of this app is _supposed_ to be an uber-simplistic placeholder for debugging or initial setup; it isn't supposed to have this level of complexity.

Recommendation:
- Reorganize the table structure to be more consistent with the way other tables are defined
- Read the table contents once at startup, then release it.  No live update - Changes to the table can be handled by restarting the app, or restarting CFE.  (Use the complete SCH from CFS if such features are required).

**Comment by skliper** [comment]
Concur with recommendations.
