### ISSUE TITLE
fails to build on Raspbian

### ISSUE THREAD

**Issue by CDKnightNASA** [nasa/sch_lab#31]
**Describe the bug**
Building sch_lab under Raspbian (a Debian variant for Raspberry Pi SBC's) fails due to alignment issues.

```
/home/pi/cFS/apps/sch_lab/fsw/src/sch_lab_app.c: In function ‘SCH_Lab_AppMain’:
/home/pi/cFS/apps/sch_lab/fsw/src/sch_lab_app.c:115:42: error: cast increases required alignment of target type [-Werror=cast-align]
                           CFE_SB_SendMsg((CFE_SB_MsgPtr_t)&SCH_CmdHeaderTable[i]);
                                          ^
```

**To Reproduce**
Build on Raspbian.

**Expected behavior**
Error-free compile.

**Code snips**
If applicable, add references to the software.

**System observed on:**
Raspberry Pi Zero W.

**Additional context**

**Reporter Info**
Christopher.D.Knight@nasa.gov

**Comment by jphickey** [comment]
As in the other apps, I have some fixes which are related to nasa/cfe#313 and feel free to assign this to me and just turn off -Wcast-align in your RPi build for now.
