### ISSUE TITLE
Clarify schedule table guidance

### ISSUE THREAD

**Issue by fletching** [nasa/sch_lab#44]
`sch_lab_table.c` has some guidance for creating the scheduling table, including ["Make sure the table is terminated by the SCH_LAB_END_OF_TABLE entry"](https://github.com/nasa/sch_lab/blob/fdc1ed1a18b12a70f512be6f6b95d0b309024aff/fsw/src/sch_lab_table.c#L30). But In looking at the file history, it doesn't look like the default schedule table has included a `SCH_LAB_END_OF_TABLE` entry ever in the past year, which is as far back as that file history goes. Should that guidance be removed?

**Comment by skliper** [comment]
The loop is below, and skips entries with a PacketRate == 0.  No longer need to terminate the table with SCH_LAB_END_OF_TABLE.

https://github.com/nasa/sch_lab/blob/fdc1ed1a18b12a70f512be6f6b95d0b309024aff/fsw/src/sch_lab_app.c#L123-L135

I'll submit a PR.
