### ISSUE TITLE
"standard" table organization

### ISSUE THREAD

**Issue by CDKnightNASA** [nasa/sch_lab#49]
**Is your feature request related to a problem? Please describe.**
sch_lab should use cFS standard table organization, to better facilitate per-target tables, etc. Right now, the table source is in fsw/src and the table header definition includes CI and TO header files which are only needed by the table.

**Describe the solution you'd like**
1. Move the table source to fsw/tables
2. Remove the #includes in sch_lab_sch_tab.h
3. Rename sch_lab_sch_tab.h to sch_lab_table.h

**Describe alternatives you've considered**
none

**Additional context**
See https://github.com/nasa/sample_app for another example of how this would be structured.

**Requester Info**
Christopher.D.Knight@nasa.gov

**Comment by jphickey** [comment]
I like it as described, as long as we take care to avoid extra complexity/keep it simple.  The point of the sch_lab app is just a quick and dirty way to get going in a debug environment.  Folks who want complexity can use CFS SCH.
