### ISSUE TITLE
Transmit messages with sequence number updates

### ISSUE THREAD

**Issue by jphickey** [nasa/sch_lab#67]
**Is your feature request related to a problem? Please describe.**
Currently the `SCH_LAB_AppMain()` function invokes `CFE_SB_TransmitMsg()` to send the messages but the `IncrementSequence` parameter is set to `false`.  This means that all commands generated from SCH_LAB have the same sequence number - whatever was in the table, probably 0.

**Describe the solution you'd like**
Should increment sequence counter so the recipient sees a properly incrementing count on each message.   This can be used to detect a missed message among other things.

**Additional context**
Suggesting just changing this line (2nd parameter) from false to true:
https://github.com/nasa/sch_lab/blob/882846bb778432c8780555b9d4bef45535584174/fsw/src/sch_lab_app.c#L123

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

**Comment by skliper** [comment]
I have no objection or even reason I can think of as to why it was implemented this way.  Fine if you want to put it in this release also.
