### ISSUE TITLE
Using void ** reference

### ISSUE THREAD

**Issue by igorluppi** [nasa/sch_lab#77]
https://github.com/nasa/sch_lab/blob/4a1b72e5a3092369b49d5c65f325bc48e1f7f832/fsw/src/sch_lab_app.c#L179

According to this [reference](http://c-faq.com/ptrs/genericpp.html), we should use the CFE_TBL_GetAddress like:

```
void * ConfigTableTmp = ConfigTable;
Status = CFE_TBL_GetAddress(&ConfigTableTmp, SCH_LAB_Global.TblHandle); 
ConfigTable = ConfigTableTmp;
```

The C reference recommends this instead of (void **) casting.

**Comment by igorluppi** [comment]
Moreover, I opened the issue here once it's a valid example, but I have seen this among many apps from cfs bundle.
Another example, [TO_lab_app](https://github.com/nasa/to_lab/blob/17e4fccf6658a82af01e7b6a03fdca48cfd8c81a/fsw/src/to_lab_app.c#L188), that uses just a simple (void *) casting: ` status = CFE_TBL_GetAddress((void *)&TO_LAB_Subs, TO_SubTblHandle);` .
DS_App also does that simple (void *) casting.

**Comment by jphickey** [comment]
Note this causes an aliasing warning when using `-Wstrict-aliasing=2` and newer GCC versions.  Been making an effort to clean these up lately.
